/*! DaoXE Docs — site config (edit freely) */
window.DX_DOCS = {
  brand: 'DaoXE',
  tagline: 'AI API 网关文档',
  /** 主站 / API 源（本地预览跨域读 status；上线同源后可改为 ''） */
  apiBase: 'https://daoxe.com',
  siteUrl: 'https://daoxe.com',
  logo: 'https://pub-c7d601dad0a34aa5a4c2120181c189f9.r2.dev/logo.png',
  consoleUrl: 'https://daoxe.com/dashboard',
  pricingUrl: 'https://daoxe.com/pricing',
  rankingsUrl: 'https://daoxe.com/rankings',
  aboutUrl: 'https://daoxe.com/about',
  homeUrl: 'https://daoxe.com/',
  signInUrl: 'https://daoxe.com/sign-in',
  profileUrl: 'https://daoxe.com/profile',
  walletUrl: 'https://daoxe.com/wallet',
  settingsUrl: 'https://daoxe.com/system-settings/site/system-info',
  support: {
    telegram: 'https://t.me/daoxe_ai',
    telegramLabel: '@daoxe_ai',
    email: 'cabesalberto36216@gmail.com',
  },
  bases: [
    {
      id: 'gia',
      name: '全球优化',
      url: 'https://api.daoxe.com',
      openai: 'https://api.daoxe.com/v1',
      note: '推荐 · 全球线路',
      color: 'blue',
    },
    {
      id: 'default',
      name: '默认',
      url: 'https://daoxe.com',
      openai: 'https://daoxe.com/v1',
      note: '与官网同源',
      color: 'slate',
    },
    {
      id: 'jp',
      name: '直连',
      url: 'https://jp.daoxe.com',
      openai: 'https://jp.daoxe.com/v1',
      note: '长任务 / 超时场景',
      color: 'green',
    },
  ],
  nav: [
    {
      id: 'start',
      title: '开始使用',
      items: [
        { href: 'index.html', title: '欢迎', id: 'welcome' },
        { href: 'pages/start/quickstart.html', title: '快速开始', id: 'quickstart' },
        { href: 'pages/start/compliance.html', title: '账号与合规', id: 'compliance' },
        { href: 'pages/start/console.html', title: '控制台导览', id: 'console' },
      ],
    },
    {
      id: 'guide',
      title: '接入指南',
      items: [
        { href: 'pages/guide/register.html', title: '注册登录', id: 'register' },
        { href: 'pages/guide/topup.html', title: '充值与套餐', id: 'topup' },
        { href: 'pages/guide/keys.html', title: '创建 API 密钥', id: 'keys' },
        { href: 'pages/guide/base-url.html', title: '线路与 Base URL', id: 'base-url' },
        { href: 'pages/guide/models.html', title: '模型与分组', id: 'models' },
        { href: 'pages/guide/clients.html', title: '客户端接入总览', id: 'clients' },
        { href: 'pages/guide/claude-code.html', title: 'Claude Code', id: 'claude-code' },
        { href: 'pages/guide/codex.html', title: 'Codex CLI', id: 'codex' },
        { href: 'pages/guide/apps.html', title: '图形客户端', id: 'apps' },
        { href: 'pages/guide/verify.html', title: 'curl 验证', id: 'verify' },
        { href: 'pages/guide/errors.html', title: '常见报错', id: 'errors' },
      ],
    },
    {
      id: 'api',
      title: 'API 参考',
      items: [
        { href: 'pages/api/auth.html', title: '鉴权与请求头', id: 'auth' },
        { href: 'pages/api/routing.html', title: '线路 · 流式 · 超时', id: 'routing' },
        { href: 'pages/api/openai-chat.html', title: 'Chat Completions', id: 'openai-chat' },
        { href: 'pages/api/openai-responses.html', title: 'Responses', id: 'openai-responses' },
        { href: 'pages/api/claude.html', title: 'Claude Messages', id: 'claude' },
        { href: 'pages/api/models.html', title: '模型列表', id: 'api-models' },
        { href: 'pages/api/errors.html', title: '错误码', id: 'api-errors' },
        { href: 'pages/api/rate-limit.html', title: '限流与重试', id: 'rate-limit' },
      ],
    },
    {
      id: 'billing',
      title: '计费与用量',
      items: [
        { href: 'pages/billing/rules.html', title: '计费规则', id: 'billing-rules' },
        { href: 'pages/billing/logs.html', title: '余额与日志', id: 'billing-logs' },
        { href: 'pages/billing/pricing.html', title: '价格与分组', id: 'billing-pricing' },
        { href: 'pages/billing/topup-issues.html', title: '充值对账', id: 'topup-issues' },
      ],
    },
    {
      id: 'features',
      title: '功能说明',
      items: [
        { href: 'pages/features/wallet.html', title: '钱包与订单', id: 'wallet' },
        { href: 'pages/features/keys.html', title: '密钥管理', id: 'feat-keys' },
        { href: 'pages/features/pricing-page.html', title: '模型广场 / 定价', id: 'feat-pricing' },
        { href: 'pages/features/invite.html', title: '邀请返佣', id: 'invite' },
        { href: 'pages/features/notice.html', title: '公告与通知', id: 'notice' },
      ],
    },
    {
      id: 'support',
      title: '帮助与支持',
      items: [
        { href: 'pages/support/faq.html', title: 'FAQ', id: 'faq' },
        { href: 'pages/support/contact.html', title: '联系客服', id: 'contact' },
        { href: 'pages/support/network.html', title: '网络与访问', id: 'network' },
      ],
    },
    {
      id: 'legal',
      title: '合规与协议',
      items: [
        { href: 'pages/legal/terms.html', title: '用户协议', id: 'terms' },
        { href: 'pages/legal/privacy.html', title: '隐私政策', id: 'privacy' },
        { href: 'pages/legal/abuse.html', title: '滥用举报', id: 'abuse' },
      ],
    },
    {
      id: 'changelog',
      title: '更新与附录',
      items: [
        { href: 'pages/changelog/index.html', title: '更新日志', id: 'changelog' },
        { href: 'pages/changelog/glossary.html', title: '术语表', id: 'glossary' },
        { href: 'pages/changelog/install.html', title: '环境安装附录', id: 'install' },
      ],
    },
  ],
};
